name: nymea Raspberry Image - bookworm

on:
  push:
    branches:
    - nymea-bookworm
  workflow_dispatch:

jobs:
  image:
    name: build bookworm image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: setup build environment
      uses: docker/setup-qemu-action@v3.0.0
    - name: build
      run: |
        ls -la
        sudo apt-get update
        sudo apt-get install qemu-user-static
        which qemu-arm-static || true
        apt-cache qemu-user-static || true
        dpkg -L qemu-user-static || true
        ./build-docker.sh
        ls -la
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        draft: true
        artifacts: deploy/image*zip
        name: nymea-image
    - name: archive artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: nymea image - bookworm
        path: deploy/image*zip
